name: "Release DevContainer Templates"

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:

    deploy:
        if: ${{ github.ref == 'refs/heads/main' }}
        runs-on: ubuntu-latest
        steps:

            - name: Checkout
              uses: actions/checkout@v2

            - name: Publish
              uses: devcontainers/action@v1
              with:
                  publish-templates: "true"
                  base-path-to-templates: "./src"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
