name: "CI - Test Templates"

on:
    pull_request:

jobs:

    detect-changes:
        runs-on: ubuntu-latest
        outputs:
            templates: ${{ steps.filter.outputs.changes }}
        steps:

            - name: Filter Paths
              uses: dorny/paths-filter@v2
              id: filter
              with:
                  filters: |
                      base-alpine: ./**/base-alpine/**

    test:
        needs: [detect-changes]
        runs-on: ubuntu-latest
        continue-on-error: true
        strategy:
            matrix:
                templates: ${{ fromJSON(needs.detect-changes.outputs.templates) }}
        steps:

            - name: Checkout
              uses: actions/checkout@v4

            - name: Smoke Test for ${{ matrix.templates }}
              id: smoke_test
              uses: ./.github/actions/smoke-test
              with:
                  template: "${{ matrix.templates }}"
